# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            'Data Science Research in Biology - <br> Fall 2022'
description:      'A course for UC Merced undergraduates in data science applications for research in ecology and evolution'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /data-science-research-biology
email:            sanchez.reyes.luna@gmail.com
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Luna Luisa Sanchez Reyes and Emily Jane McTavish'
  url:            https://mctavishlab.github.io/

github:
  repo:           https://github.com/LunaSare/data-science-research-biology.git
  #               Be sure the 'Issues' feature is activated in 'Settings'
