# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Course: Data Science Research in Biology
description:      'A course for undergraduates covering computational approaches to data science in biology'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /data-science-research-biology
email:            sanchez.reyes.luna@gmail.com
author:
  name:           'Luna Luisa Sanchez Reyes and Emily Jane McTavish'
  url:            https://mctavishlab.github.io/

github:
  repo:           https://github.com/LunaSare/data-science-research-biology.git
  #               Be sure the 'Issues' feature is activated in 'Settings'
